version: '3'
services:
  jotihunt:
    image: jasperroel/jotihunt-site
    depends_on:
    - db
    environment:
      DATABASE_URL: postgres://jotihunt:jotihunt@db:5432/jotihunt
    expose:
    - "80"
    ports:
    - "8080:80"
  db:
    image: postgres
    environment:
      POSTGRES_USER: jotihunt
      POSTGRES_PASSWORD: jotihunt
